# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -la'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PS1='\[\e[1;31m\][\u:\h\[\e[1;30m\] \W\[\e[1;31m\]]\[\e[1;31m\]\$\[\e[m\]'
